version: '3.3'

services:
  # Telegraf collects the data
  telegraf:
    image: telegraf:1.4.0
    configs:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
    networks:
      - hostnet
    # restart: always

  # InfluxDB stores the data
  influxdb:
    image: influxdb:1.3.5
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - hostnet
    # restart: always

  # Chronograf is the GUI to view the data
  chronograf:
    image: chronograf:1.3.8
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    volumes:
      - chronograf-data:/var/lib/chronograf
    networks:
      - hostnet
    # restart: always

  # Kapacitor is the alerting engine
  kapacitor:
    image: kapacitor:1.3.3
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    configs:
      - ./config/kapacitor.conf:/etc/kapacitor/kapacitor.conf
    ports:
      - "9092:9092"
     volumes:
      - kapacitor-data:/var/lib/kapacitor
    networks:
      - hostnet
    # restart: always

  # home-grown node process that serves up data
  # and handles other miscelaneous tasks
  manager:
    image: whmountinas/sensorpi-manager:latest
    volumes:
      - /sys:/sys
      - sensorpi-manager-data
    ports:
      - "80:3000"
    # restart: always
  networks:
    - hostnet

volumes:
  influxdb-data:
  chronograf-data:
  kapacitor-data:
  sensorpi-manager-data:

networks:
  hostnet:
    driver: bridge
    external:
      name: host