[calibration.temperature]
coefficient = 1
offset = 0

[calibration.humidity]
coefficient = 1
offset = 0

# example rule to always keep port 1 on
[[rules]]
outputs = {1 = 1}

# example rule to enable port 2 when temperature rises above 22C
[[rules]]
condition = "temperature > 26"
outputs = {2 = 1}

# now disable port 2 when the temperature goes down
[[rules]]
condition = "temperature < 25"
outputs = {2 = 0}
